### ISSUE TITLE
Use WithTimeout context when call elasticsearch api methods

### ISSUE THREAD

**Issue by maknihamdi** [Carrefour-Group/elastic-phenix-operator#4]
for ex:
`	response, err := esapi.IndicesPutTemplateRequest{Name: templateName, Body: strings.NewReader(model), IncludeTypeName: shouldIncludeTypeName}.Do(context.Background(), es.Client)
`

we shoud use a context.WithTimeout instead of context.Background to avoir longrunning http requests

**Comment by wmellouli** [comment]
@maknihamdi I refactored to use the parent context from controllers inside Elasticsearch functions.
I added a `context.WithTimeout` only for main functions called from controllers.  The PR: https://github.com/Carrefour-Group/elastic-phenix-operator/pull/7
